# -*- coding: utf-8 -*-
"""Predicy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11UAn9unEbVUfx82MPu46FYxp1KO_i4i1
"""

from keras.preprocessing import image
from keras.models import load_model
import numpy as np

# Load your trained model
model = load_model('C:\Users\Bhavaneeshwaran\Music\IMageDetection\trained_model.h5')

# Load and preprocess the image for prediction
img_path = 'A:\RAJASTHAN\IMageDetection\test\fake_1.jpg'  # Change this to the path of your test image
img = image.load_img(img_path, target_size=(299, 299))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array /= 255.  # Normalize the image

# Make predictions
predictions = model.predict(img_array)

# Print the predicted probability
print(f"Predicted Probability: {predictions[0]}")

# Get the predicted class
predicted_class = int(predictions[0] > 0.5)

# Print the predicted class
if predicted_class == 1:
    print("The image is predicted to be a deepfake.")
else:
    print("The image is predicted to be real.")
